### ISSUE TITLE
[Unity] Wifi icons

### ISSUE THREAD

**Issue by RR1991** [varlesh/papirus-suite#113]
Unless one is using a dark theme, the Wifi icons in the indicator panel are almost invisible.
I am referring to the icons that indicate the signal strength and open or protected network. These are white, and therefore not visible when using arc-darker for example. Perhaps these icons could be made a light shade of grey, or a stronger outline, so that they will be visible for dark and light themes?

**Comment by varlesh** [comment]
You mean colors indicators on panel menu? It's impossible, because themes used monochrome style and Unity not use symbolic icons on menu.
But, you can replace needed icons. Additional variant available on Papirus-GTK/22x22/panel-dark:
https://github.com/varlesh/papirus-suite/tree/master/gtk-icons/Papirus-GTK/22x22/panel-dark

**Comment by RR1991** [comment]
I see. I have replaced the icons with the one from the ubuntu mobile icon theme, worked perfectly. Thanks for the tip. Beautiful icon theme!
